version: '3'

services:
  server:
    build: 
      context: .
    container_name: backend
    env_file:
      - ./.env
    depends_on:
      - hasyadb
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src/:/usr/app/backend/src/
    command: ["yarn", "dev"]

  hasyadb:
    image: postgres:alpine
    container_name: hasyadb
    env_file: 
      - ./.env
    ports:
      - ${DB_PORT}:${DB_PORT}

    environment:
      POSTGRES_DB: hasya # ${DB_DATABASE}
      POSTGRES_PASSWORD: postgres # ${DB_PASSWORD}
      PSOTGRES_USER: postgres # ${DB_USER}

    volumes:
      - hasyadb:/var/lib/postresql/data

volumes: 
  hasyadb: